services:
  - type: web
    name: bibloteca
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run db:push && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bibloteca-db
          property: connectionString
      - key: AI_INTEGRATIONS_OPENAI_API_KEY
        sync: false
      - key: AI_INTEGRATIONS_OPENAI_BASE_URL
        sync: false
databases:
  - name: bibloteca-db
    databaseName: bibloteca
    user: bibloteca_user
